// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: count_primes.proto

package P2_primes

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FileServer_GetFileSegment_FullMethodName = "/proto.FileServer/GetFileSegment"
)

// FileServerClient is the client API for FileServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileServerClient interface {
	// Define a method within your service
	GetFileSegment(ctx context.Context, in *GetFileSegmentRequest, opts ...grpc.CallOption) (FileServer_GetFileSegmentClient, error)
}

type fileServerClient struct {
	cc grpc.ClientConnInterface
}

func NewFileServerClient(cc grpc.ClientConnInterface) FileServerClient {
	return &fileServerClient{cc}
}

func (c *fileServerClient) GetFileSegment(ctx context.Context, in *GetFileSegmentRequest, opts ...grpc.CallOption) (FileServer_GetFileSegmentClient, error) {
	stream, err := c.cc.NewStream(ctx, &FileServer_ServiceDesc.Streams[0], FileServer_GetFileSegment_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &fileServerGetFileSegmentClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FileServer_GetFileSegmentClient interface {
	Recv() (*GetFileSegmentResponse, error)
	grpc.ClientStream
}

type fileServerGetFileSegmentClient struct {
	grpc.ClientStream
}

func (x *fileServerGetFileSegmentClient) Recv() (*GetFileSegmentResponse, error) {
	m := new(GetFileSegmentResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FileServerServer is the server API for FileServer service.
// All implementations must embed UnimplementedFileServerServer
// for forward compatibility
type FileServerServer interface {
	// Define a method within your service
	GetFileSegment(*GetFileSegmentRequest, FileServer_GetFileSegmentServer) error
	mustEmbedUnimplementedFileServerServer()
}

// UnimplementedFileServerServer must be embedded to have forward compatible implementations.
type UnimplementedFileServerServer struct {
}

func (UnimplementedFileServerServer) GetFileSegment(*GetFileSegmentRequest, FileServer_GetFileSegmentServer) error {
	return status.Errorf(codes.Unimplemented, "method GetFileSegment not implemented")
}
func (UnimplementedFileServerServer) mustEmbedUnimplementedFileServerServer() {}

// UnsafeFileServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileServerServer will
// result in compilation errors.
type UnsafeFileServerServer interface {
	mustEmbedUnimplementedFileServerServer()
}

func RegisterFileServerServer(s grpc.ServiceRegistrar, srv FileServerServer) {
	s.RegisterService(&FileServer_ServiceDesc, srv)
}

func _FileServer_GetFileSegment_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetFileSegmentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FileServerServer).GetFileSegment(m, &fileServerGetFileSegmentServer{stream})
}

type FileServer_GetFileSegmentServer interface {
	Send(*GetFileSegmentResponse) error
	grpc.ServerStream
}

type fileServerGetFileSegmentServer struct {
	grpc.ServerStream
}

func (x *fileServerGetFileSegmentServer) Send(m *GetFileSegmentResponse) error {
	return x.ServerStream.SendMsg(m)
}

// FileServer_ServiceDesc is the grpc.ServiceDesc for FileServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.FileServer",
	HandlerType: (*FileServerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetFileSegment",
			Handler:       _FileServer_GetFileSegment_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "count_primes.proto",
}

const (
	Dispatcher_GetJob_FullMethodName = "/proto.Dispatcher/GetJob"
)

// DispatcherClient is the client API for Dispatcher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DispatcherClient interface {
	GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error)
}

type dispatcherClient struct {
	cc grpc.ClientConnInterface
}

func NewDispatcherClient(cc grpc.ClientConnInterface) DispatcherClient {
	return &dispatcherClient{cc}
}

func (c *dispatcherClient) GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error) {
	out := new(GetJobResponse)
	err := c.cc.Invoke(ctx, Dispatcher_GetJob_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DispatcherServer is the server API for Dispatcher service.
// All implementations must embed UnimplementedDispatcherServer
// for forward compatibility
type DispatcherServer interface {
	GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error)
	mustEmbedUnimplementedDispatcherServer()
}

// UnimplementedDispatcherServer must be embedded to have forward compatible implementations.
type UnimplementedDispatcherServer struct {
}

func (UnimplementedDispatcherServer) GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJob not implemented")
}
func (UnimplementedDispatcherServer) mustEmbedUnimplementedDispatcherServer() {}

// UnsafeDispatcherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DispatcherServer will
// result in compilation errors.
type UnsafeDispatcherServer interface {
	mustEmbedUnimplementedDispatcherServer()
}

func RegisterDispatcherServer(s grpc.ServiceRegistrar, srv DispatcherServer) {
	s.RegisterService(&Dispatcher_ServiceDesc, srv)
}

func _Dispatcher_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatcherServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dispatcher_GetJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatcherServer).GetJob(ctx, req.(*GetJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Dispatcher_ServiceDesc is the grpc.ServiceDesc for Dispatcher service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Dispatcher_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Dispatcher",
	HandlerType: (*DispatcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetJob",
			Handler:    _Dispatcher_GetJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "count_primes.proto",
}

const (
	Consolidator_PushPrimes_FullMethodName = "/proto.Consolidator/PushPrimes"
)

// ConsolidatorClient is the client API for Consolidator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConsolidatorClient interface {
	PushPrimes(ctx context.Context, in *PushPrimesRequest, opts ...grpc.CallOption) (*PushPrimesResponse, error)
}

type consolidatorClient struct {
	cc grpc.ClientConnInterface
}

func NewConsolidatorClient(cc grpc.ClientConnInterface) ConsolidatorClient {
	return &consolidatorClient{cc}
}

func (c *consolidatorClient) PushPrimes(ctx context.Context, in *PushPrimesRequest, opts ...grpc.CallOption) (*PushPrimesResponse, error) {
	out := new(PushPrimesResponse)
	err := c.cc.Invoke(ctx, Consolidator_PushPrimes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsolidatorServer is the server API for Consolidator service.
// All implementations must embed UnimplementedConsolidatorServer
// for forward compatibility
type ConsolidatorServer interface {
	PushPrimes(context.Context, *PushPrimesRequest) (*PushPrimesResponse, error)
	mustEmbedUnimplementedConsolidatorServer()
}

// UnimplementedConsolidatorServer must be embedded to have forward compatible implementations.
type UnimplementedConsolidatorServer struct {
}

func (UnimplementedConsolidatorServer) PushPrimes(context.Context, *PushPrimesRequest) (*PushPrimesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushPrimes not implemented")
}
func (UnimplementedConsolidatorServer) mustEmbedUnimplementedConsolidatorServer() {}

// UnsafeConsolidatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsolidatorServer will
// result in compilation errors.
type UnsafeConsolidatorServer interface {
	mustEmbedUnimplementedConsolidatorServer()
}

func RegisterConsolidatorServer(s grpc.ServiceRegistrar, srv ConsolidatorServer) {
	s.RegisterService(&Consolidator_ServiceDesc, srv)
}

func _Consolidator_PushPrimes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushPrimesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsolidatorServer).PushPrimes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Consolidator_PushPrimes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsolidatorServer).PushPrimes(ctx, req.(*PushPrimesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Consolidator_ServiceDesc is the grpc.ServiceDesc for Consolidator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Consolidator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Consolidator",
	HandlerType: (*ConsolidatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushPrimes",
			Handler:    _Consolidator_PushPrimes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "count_primes.proto",
}
